# Generated by Django 6.0.4 on 2026-04-30 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacemembership',
            name='department',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='workspacemembership',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workspacemembership',
            name='job_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='workspacemembership',
            name='last_active_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workspacemembership',
            name='tasks_completed_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workspacemembership',
            name='tasks_created_count',
            field=models.IntegerField(default=0),
        ),
    ]
